/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://support.hdfgroup.org/ftp/HDF5/releases.  *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Aug 27, 2017
 *			dojo <dojo@dojos-MacBook-Pro.local>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.10.1\n"
	"                  Configured on: Sun Aug 27 12:21:06 PDT 2017\n"
	"                  Configured by: dojo@dojos-MacBook-Pro.local\n"
	"                    Host system: x86_64-apple-darwin17.0.0\n"
	"              Uname information: Darwin dojos-MacBook-Pro.local 17.0.0 Darwin Kernel Version 17.0.0: Wed Aug 16 20:06:51 PDT 2017; root:xnu-4570.1.45~23/RELEASE_X86_64 x86_64 i386 MacBookPro8,1 Darwin\n"
	"                       Byte sex: little-endian\n"
	"             Installation point: /usr/local/Cellar/hdf5/1.10.1\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"                     Build Mode: production\n"
	"              Debugging Symbols: no\n"
	"                        Asserts: no\n"
	"                      Profiling: no\n"
	"             Optimization Level: high\n"
	"\n"
	"Linking Options:\n"
	"----------------\n"
	"                      Libraries: static, shared\n"
	"  Statically Linked Executables: \n"
	"                        LDFLAGS: -L/usr/local/opt/openblas/lib -L/usr/local/opt/llvm/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/portable-expat/lib \n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: -lz -ldl -lm \n"
	"                       Archiver: ar\n"
	"                         Ranlib: ranlib\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                              C: yes\n"
	"                     C Compiler: /usr/bin/cc\n"
	"                       CPPFLAGS: -I/usr/local/opt/openblas/include -I/usr/local/opt/llvm/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/portable-expat/include \n"
	"                    H5_CPPFLAGS:   -DNDEBUG -UH5_DEBUG_API\n"
	"                    AM_CPPFLAGS: \n"
	"                        C Flags: -fomit-frame-pointer -funroll-loops  -ffast-math -Ofast -fno-signed-zeros -ffp-contract=fast -mmmx -msse -flto  \n"
	"                     H5 C Flags:     \n"
	"                     AM C Flags: \n"
	"               Shared C Library: yes\n"
	"               Static C Library: yes\n"
	"\n"
	"\n"
	"                        Fortran: no\n"
	"\n"
	"                            C++: no\n"
	"\n"
	"                           Java: no\n"
	"\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: no\n"
	"             High-level library: yes\n"
	"                   Threadsafety: no\n"
	"            Default API mapping: v110\n"
	" With deprecated public symbols: yes\n"
	"         I/O filters (external): deflate(zlib)\n"
	"                            MPE: no\n"
	"                     Direct VFD: no\n"
	"                        dmalloc: no\n"
	" Packages w/ extra debug output: none\n"
	"                    API tracing: no\n"
	"           Using memory checker: no\n"
	"Memory allocation sanity checks: no\n"
	"            Metadata trace file: no\n"
	"         Function stack tracing: no\n"
	"      Strict file format checks: no\n"
	"   Optimization instrumentation: no\n"
;

